### ISSUE TITLE
Can't repeat "vina>cross-docking>SR1" in Tabel6

### ISSUE THREAD

**Issue by zchwang** [sc8668/GenScore#5]
Hi,
I ran GenScore on PDBbind-crossdock-core for testing (The model I tested was GT_ft_1.0_1.pth, using the default parameters for everything else.). However, for the decoys generated by vina, 505 receptor-ligand pairs (1343 in total) reported errors:
"""
Traceback (most recent call last):
  File ".../GenScore/GenScore/example/genscore.py", line 256, in <module>
    main()
  File ".../GenScore/GenScore/example/genscore.py", line 237, in main
    ids, scores = scoring(prot=inargs.prot,
  File ".../GenScore/GenScore/example/genscore.py", line 82, in scoring
    data = VSDataset(ligs=lig,
  File ".../GenScore/GenScore/example/../GenScore/data/data.py", line 178, in __init__
    self.ids, self.gls = zip(*filter(lambda x: x[1] != None, zip(self.idsx, self.gls)))
ValueError: not enough values to unpack (expected 2, got 0)
"""
In all the cases where score can be generated, I calculated that the cross-docking SR1 is only 0.463 (0.59 reported in paper), and the SR1 of redocking is 0.680.

What problems do I need to correct when running genscore?

Best regards.

**Comment by sc8668** [comment]
Can you reproduce the results when the docking poses are generated by Surflex-Dock or Glide SP?    The errors may come from those poor structures generated by Vina (some structures in .pdbqt format cannot be well recognized by RDKit though they have been processed by Open Babel).   Additionally, it should be noted that to better calculate the scoring powers, the SR1 calculated in Table 6 is based on the idea of ensemble docking, where the five complexes in the same cluster is considered as a group, thus resulting in ~285 samples rather than 1343.

**Comment by zchwang** [comment]
Thank you for your reply.
What I understand now is that in a cluster (57 in total), there are on average 5 subsets accoring to the lignad ID, and all poses of a specific ligand across multiple receptor as a case. So there are 285 cases. If the receptor ID is the same as the ligand id, do these poses be included in the evaluation of cross-docking? Also, what tools do you use to calculate rmsd?
Looking forward to your reply


> Can you reproduce the results when the docking poses are generated by Surflex-Dock or Glide SP? The errors may come from those poor structures generated by Vina (some structures in .pdbqt format cannot be well recognized by RDKit though they have been processed by Open Babel). Additionally, it should be noted that to better calculate the scoring powers, the SR1 calculated in Table 6 is based on the idea of ensemble docking, where the five complexes in the same cluster is considered as a group, thus resulting in ~285 samples rather than 1343.

**Comment by sc8668** [comment]
Yes, just as you understand. Of course the crystalized ligand should be excluded in the evaluation of cross-docking performance. The pose with the highest score among all the poses of these four complexes is regarded as the final pose for this group. 
The RMSDs for the poses in PDBbind-crossdock-core are calculated through the obrms utility in OpenBabel. Please refer to our previous paper (https://doi.org/10.1186/s13321-021-00560-w).  Of course, some tools such as spyrmsd (https://githu b.com/RMeli/pyrmsd) and DockRMSD (https://zhanglab.ccmb.med.umich.edu/DockRMSD/) can also produce substantially consistent results.

**Comment by zchwang** [comment]
OK. Thanks again for your reply.

Best regards,
Zechen
