### ISSUE TITLE
details about your ex: 1qkt 

### ISSUE THREAD

**Issue by CLG68** [sc8668/GenScore#7]
Hi,
I am trying to figure out how to use GenScore based on your example: 1qkt.  Could you give me some details about the files, please?
I guess you prepared the files (1qkt_p.pdb & 1qkt_l.sdf) from 1qkt so the estrogen nuclear receptor with its ligand estrogen, using Maestro.  Did you get 1qkt from RCSB pdb or from pdb-redo?  Did you apply some minimization on his complex during preparation? 

How did you generate: 1qkt_decoys.sdf?  Why is it used with -gen_pocket... the binding pocket is selected based on both 1qkt_l.sdf and 1qkt_decoys.sdf? 

GenScore accepts ligand files only in sdf or also in other format such as mol2?

Thanks for your help

**Comment by sc8668** [comment]
We fetched 1qkt from RCSB pdb and then prepared it using the Protein Preparation Wizard module in Maestro (with minor minimization)，and then save the protein and the crystalized ligand as 1qkt_p.pdb and 1qkt_l.sdf, respectively. 
1qkt_decoys.sdf is fetched from CASF-2016 benchmark (http://www.pdbbind.org.cn/casf.php), and here we just use it as an example, and it could be replaced with any docked poses.   The binding pocket is selected based on 1qkt_l.sdf, and 1qkt_decoys.sdf is just the docked ligands ready to be rescored by our models.
Other formats such as mol2 and pdb are also acceptable, but I recommend you to use the ligand in sdf.

**Comment by CLG68** [comment]
Thank you very much.  
I'm trying to create an environment to run it.  However, I cannot use venv as I'm not able to install openbabel using PIP, for a reason I do not understand.  Under a conda environment, it has problems with the very old version of numpy (1.20.3) and pandas (1.0.3) vs dependencies of the other packages.  I'll reinstall one of my PC and install everything at base, maybe it will solve the problem.

Thank you again for your help

**Comment by CLG68** [comment]
Do you have a "Dockerized" version of GenScore?

**Comment by CLG68** [comment]
I solved the environment problem, see my new post.
