### ISSUE TITLE
Cannot reproduce publicated data

### ISSUE THREAD

**Issue by gianfi12** [sc8668/GenScore#8]
Hi everyone,
I'm trying to reproduce the numbers I've found in this publication about [GenScore](https://doi.org/10.1039%2Fd3sc02044d) .
I'm interested in the Enrichment Factor. I've started my analysis by downloading CASF-2016 from the official website.
The following is the process I followed to try and reproduce the data.
For each of the Binders of the CASF available inside `CASF-2016/decoys_screening` I've computed the scoring of all ligands inside each folder using the following command:
[casf_output_ef.txt](https://github.com/sc8668/GenScore/files/12768397/casf_output_ef.txt)

`python3.8 ./example/genscore.py -p CASF-2016/coreset/<target>/<target>_pocket.pdb -l CASF_2016/decoys_screening/<target>/ligands.mol2 -e gatedgcn -m ./trained_models/GatedGCN_0.5_1.pth -o <out_file>`
Now that I have all the scores computed by GenScore, I've computed the enrichment factor with the following:
` python2 CASF-2016/power_screening/forward_screening_power.py -c CoreSet.dat -s <genscore_results_folder> -t TargetInfo.dat -p 'positive' -o 'GenScore'`
The problem I get is from the output of this script (I'm attaching the output I got):
`
Average enrichment factor among top 1% = 8.11
Average enrichment factor among top 5% = 3.36
Average enrichment factor among top 10% = 2.31
The best ligand is found among top 1% candidates for 15 cluster(s);
success rate = 26.3%
The best ligand is found among top 5% candidates for 24 cluster(s);
success rate = 42.1%
The best ligand is found among top 10% candidates for 28 cluster(s);
success rate = 49.1%
`
Which is different from the number I've found in the publication

What am I missing?

Thank you in advance for all the help.

**Comment by sc8668** [comment]
Please use the buit-in script to generate the pocket with 10.0 Å around the crystalized ligand first and then use GenScore for rescoring.

**Comment by gianfi12** [comment]
Hi,
Thank you very much, I've followed your recommendation
> Please use the buit-in script to generate the pocket with 10.0 Å around the crystalized ligand first and then use GenScore for rescoring.

And now I've been able to reproduce the results!
